#!/bin/sh
#
# Simple command that helps me convert Markdown to MediaWiki Markup. 
#
# Note that it outputs the result into the terminal, not into a file
#
# Usage: md2mw (markdown file) (desired txt file name) 
#

pandoc "$1" -f markdown -t mediawiki -s -o "$2" 